name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project for production
        env:
          NODE_ENV: production
        run: npm run build:prod



  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenSSH Client
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client

      - name: Deploy to server
        env:
          SSH_PASSWORD: Maher3314156+
          
        run: |
          $env:SSH_PASSWORD | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString | Out-File "$env:USERPROFILE\.ssh\password.txt"
          sshpass -f "$env:USERPROFILE\.ssh\password.txt" ssh -o StrictHostKeyChecking=no Maher@devscape.online "cd C:\inetpub\maher_nest && git pull origin main && npm install --production --legacy-peer-deps && npm run build:prod && iisreset"
