name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PASSWORD: Maher3314156+
        run: |
          $password = ConvertTo-SecureString $env:SSH_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ('Maher', $password)
          Invoke-Command -ScriptBlock {
            cd C:\inetpub\maher_nest
            git pull origin main
            npm install
            npm run build
            iisreset
          } -Credential $credential -ComputerName devscape.online
